// Renders assets/brand PNGs with rsvg-convert and writes services/brand-icons.mjs,
// which the relay Worker serves. Run after changing an SVG in assets/brand.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';

const brand = new URL('../assets/brand/', import.meta.url);
const file = (name) => new URL(name, brand).pathname;
for (const [source, size, output] of [['icon.svg', 32, 'favicon-32.png'],
  ['icon-square.svg', 180, 'apple-touch-icon.png'], ['icon.svg', 512, 'icon-512.png']]) {
  execFileSync('rsvg-convert', ['-w', String(size), '-h', String(size), file(source), '-o', file(output)]);
}
const png = (name) => fs.readFileSync(file(name)).toString('base64');
const svg = fs.readFileSync(file('icon.svg'), 'utf8').trim();
fs.writeFileSync(new URL('../services/brand-icons.mjs', import.meta.url), `// Generated by scripts/build-icons.mjs from assets/brand. Do not edit by hand.
const SVG = ${JSON.stringify(svg)};
const PNG = {
  favicon: '${png('favicon-32.png')}',
  appleTouch: '${png('apple-touch-icon.png')}',
  large: '${png('icon-512.png')}',
};

const ICONS = {
  '/favicon.svg': ['image/svg+xml', () => SVG],
  '/favicon.ico': ['image/png', () => Buffer.from(PNG.favicon, 'base64')],
  '/favicon-32.png': ['image/png', () => Buffer.from(PNG.favicon, 'base64')],
  '/apple-touch-icon.png': ['image/png', () => Buffer.from(PNG.appleTouch, 'base64')],
  '/icon-512.png': ['image/png', () => Buffer.from(PNG.large, 'base64')],
};

export const ICON_LINKS = '<link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="icon" href="/favicon-32.png" sizes="32x32" type="image/png"><link rel="apple-touch-icon" href="/apple-touch-icon.png">';

export function iconResponse(request) {
  if (!['GET', 'HEAD'].includes(request.method)) return null;
  const icon = ICONS[new URL(request.url).pathname];
  if (!icon) return null;
  return new Response(request.method === 'HEAD' ? null : icon[1](), { headers: {
    'Content-Type': icon[0], 'Cache-Control': 'public, max-age=86400',
    'X-Content-Type-Options': 'nosniff',
  } });
}
`);
